let chromium;
try {
  ({ chromium } = require('playwright'));
} catch (error) {
  const modulePath = process.env.DEMO_PLAYWRIGHT_MODULE;
  if (!modulePath) throw error;
  ({ chromium } = require(modulePath));
}
const fs=require('node:fs');
const path=require('node:path');
const base='http://127.0.0.1:8810';
const output=__dirname;
(async()=>{
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1,acceptDownloads:true});
  const errors=[],consoleErrors=[],failedRequests=[],mutations=[],checks=[],screenshots=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});
  page.on('requestfailed',request=>failedRequests.push({url:request.url(),error:request.failure()}));
  page.on('request',request=>{if(!['GET','HEAD','OPTIONS'].includes(request.method()))mutations.push({method:request.method(),url:request.url()});});
  const check=(name,passed,detail)=>checks.push({name,passed,...(detail===undefined?{}:{detail})});
  const get=async route=>{const response=await page.request.get(base+route);if(!response.ok())throw new Error(`${route}: ${response.status()}`);return response.json();};
  const runs=await get('/api/incidents/runs');
  const run=runs.runs.find(run=>run.id===process.env.INCIDENT_RUN)||runs.runs.find(run=>run.id.startsWith('incident-'));
  if(!run)throw new Error('No prepared incident run available; this check never prepares logs.');
  const params=new URLSearchParams({run_id:run.id,actor:'bob',capture:'full'});
  const baseline=await get('/api/incidents/analyze?'+params);
  const beforeIds=baseline.timeline.map(event=>event.event_id);
  await page.goto(base+'/#incidents',{waitUntil:'networkidle'});
  await page.locator('#incident-results').waitFor();
  if(await page.locator('#incident-run').inputValue()!==run.id){await page.locator('#incident-run').selectOption(run.id);await page.locator('#incident-analyze').click();await page.locator('#incident-status.success').waitFor();}
  check('six_tabs_available',await page.locator('.nav-item').count()===6);
  check('direct_hash_opens_incident_tab',await page.locator('#tab-incidents').isVisible());
  check('replay_controls_hidden_in_incident_tab',!await page.locator('.experiment-bar').isVisible());
  check('stored_source_is_readonly',baseline.source==='stored_postgresql_records_only'&&baseline.network_replay===false);
  check('separate_prepare_control_visible',await page.locator('#incident-prepare').isVisible());
  for(const [key,value]of Object.entries(baseline.summary)){const locator=page.locator(`[data-incident-metric="${key}"]`);if(await locator.count())check('full_metric_'+key,(await locator.innerText())===value.toLocaleString('ko-KR'),{observed:value});}
  check('endpoint_row_count',await page.locator('#incident-api-table tbody tr').count()===baseline.api_calls.length);
  check('timeline_row_count',await page.locator('#incident-timeline tbody tr').count()===baseline.timeline.length);
  check('subject_card_count',await page.locator('#incident-subjects .link-card').count()===baseline.subjects.length);
  check('confirmed_fields_separate_from_all_fields',await page.locator('#incident-subjects .incident-confirmed-fields').count()===baseline.subjects.length);
  const confirmedFieldCount=baseline.subjects.reduce((count,subject)=>count+(subject.confirmed_fields||[]).length,0);
  check('confirmed_fields_match_stored_api',await page.locator('#incident-subjects .incident-confirmed-fields .tag').count()===confirmedFieldCount);
  check('completeness_unknown_visible',(await page.locator('#incident-coverage').innerText()).includes('로그 완전성 미확인'));
  check('full_desktop_no_page_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:path.join(output,'desktop-overview.png'),fullPage:false});screenshots.push('desktop-overview.png');
  await page.screenshot({path:path.join(output,'desktop-full.png'),fullPage:true});screenshots.push('desktop-full.png');
  await page.locator('#incident-timeline tbody tr').first().click();
  check('timeline_evidence_opens',await page.locator('#incident-evidence').isVisible());
  check('full_evidence_has_response',(await page.locator('#incident-evidence').innerText()).includes('response_redacted'));
  await page.locator('#incident-evidence').screenshot({path:path.join(output,'desktop-evidence.png')});screenshots.push('desktop-evidence.png');
  await page.locator('#incident-close-evidence').click();
  check('evidence_closes',!await page.locator('#incident-evidence').isVisible());
  const reportURL=await page.locator('#incident-report').getAttribute('href');
  const markdown=await page.request.get(base+reportURL);
  const markdownText=await markdown.text();
  check('markdown_download_endpoint',markdown.status()===200&&markdownText.includes(run.id)&&markdownText.includes('분석 중 API 재호출: 없음'));
  const downloadPromise=page.waitForEvent('download');await page.locator('#incident-report').click();const download=await downloadPromise;
  await download.saveAs(path.join(output,'browser-downloaded-report.md'));
  check('markdown_browser_download',fs.existsSync(path.join(output,'browser-downloaded-report.md')));
  await page.locator('#incident-capture').selectOption('metadata_only');
  check('changed_filter_hides_old_result',!await page.locator('#incident-results').isVisible());
  await page.locator('#incident-analyze').click();await page.locator('#incident-status.success').waitFor();
  const meta=await get('/api/incidents/analyze?'+new URLSearchParams({run_id:run.id,actor:'bob',capture:'metadata_only'}));
  for(const key of ['confirmed_policy_requests','returned_subjects','confirmed_exposure_subjects'])check('metadata_'+key+'_unknown',await page.locator(`[data-incident-metric="${key}"]`).innerText()==='알 수 없음'&&meta.summary[key]===null);
  check('metadata_retains_request_count',await page.locator('[data-incident-metric="logged_requests"]').innerText()===baseline.summary.logged_requests.toLocaleString('ko-KR'));
  check('metadata_no_subject_cards',await page.locator('#incident-subjects .link-card').count()===0);
  check('metadata_explains_unknown_subjects',(await page.locator('#incident-subjects').innerText()).includes('실제 반환됐다는 증거는 아닙니다'));
  check('metadata_model_section_hidden',!await page.locator('#incident-model-section').isVisible());
  await page.screenshot({path:path.join(output,'desktop-metadata-only.png'),fullPage:true});screenshots.push('desktop-metadata-only.png');
  await page.locator('#incident-timeline tbody tr').first().click();
  check('metadata_evidence_no_response_payload',!(await page.locator('#incident-evidence').innerText()).includes('response_redacted'));
  await page.reload({waitUntil:'networkidle'});await page.locator('#incident-status.success').waitFor();
  check('scope_persists_on_reload',await page.locator('#incident-capture').inputValue()==='metadata_only'&&await page.locator('#incident-run').inputValue()===run.id);
  await page.locator('#incident-capture').selectOption('full');await page.locator('#incident-actor').selectOption('admin');await page.locator('#incident-analyze').click();await page.locator('#incident-status.success').waitFor();
  const admin=await get('/api/incidents/analyze?'+new URLSearchParams({run_id:run.id,actor:'admin',capture:'full'}));
  check('admin_scope_from_stored_logs',await page.locator('[data-incident-metric="logged_requests"]').innerText()===String(admin.summary.logged_requests)&&await page.locator('[data-incident-metric="confirmed_policy_requests"]').innerText()===String(admin.summary.confirmed_policy_requests),admin.summary);
  await page.locator('#incident-actor').selectOption('all');await page.locator('#incident-analyze').click();await page.locator('#incident-status.success').waitFor();
  const all=await get('/api/incidents/analyze?'+new URLSearchParams({run_id:run.id,actor:'all',capture:'full'}));
  check('all_actor_scope_matches_api',await page.locator('[data-incident-metric="logged_requests"]').innerText()===String(all.summary.logged_requests),all.summary);
  await page.locator('#incident-actor').selectOption('bob');await page.locator('#incident-analyze').click();await page.locator('#incident-status.success').waitFor();
  await page.setViewportSize({width:390,height:844});await page.locator('.nav-item[data-tab="incidents"]').click();await page.evaluate(()=>scrollTo(0,0));
  check('mobile_full_no_page_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:path.join(output,'mobile-overview.png'),fullPage:false});screenshots.push('mobile-overview.png');
  await page.locator('#incident-stats').screenshot({path:path.join(output,'mobile-metrics.png')});screenshots.push('mobile-metrics.png');
  await page.screenshot({path:path.join(output,'mobile-full.png'),fullPage:true});screenshots.push('mobile-full.png');
  await page.locator('#incident-capture').selectOption('metadata_only');await page.locator('#incident-analyze').click();await page.locator('#incident-status.success').waitFor();
  check('mobile_metadata_no_page_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:path.join(output,'mobile-metadata-only.png'),fullPage:true});screenshots.push('mobile-metadata-only.png');
  for(const tab of ['overview','findings','events','mapping','model']){await page.locator(`.nav-item[data-tab="${tab}"]`).click();check('existing_'+tab+'_still_opens',await page.locator('#tab-'+tab).isVisible());check('existing_'+tab+'_mobile_no_page_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
  await page.locator('.nav-item[data-tab="incidents"]').click();await page.locator('#incident-capture').selectOption('full');await page.locator('#incident-analyze').click();await page.locator('#incident-status.success').waitFor();
  const final=await get('/api/incidents/analyze?'+params);
  check('stored_event_ids_unchanged',JSON.stringify(beforeIds)===JSON.stringify(final.timeline.map(event=>event.event_id)));
  check('stored_summary_unchanged',JSON.stringify(baseline.summary)===JSON.stringify(final.summary));
  check('analysis_sends_no_mutating_http_requests',mutations.length===0,mutations);
  check('no_javascript_errors',errors.length===0,errors);
  check('no_console_errors',consoleErrors.length===0,consoleErrors);
  check('no_failed_requests',failedRequests.length===0,failedRequests);
  const report={status:checks.every(check=>check.passed)?'PASS':'FAIL',checked_at:new Date().toISOString(),browser:await browser.version(),run_id:run.id,source:'Actual localhost UI and stored API records. No prepare or replay action used.',before_summary:baseline.summary,metadata_summary:meta.summary,checks,screenshots,mutating_requests:mutations};
  fs.writeFileSync(path.join(output,'ui-validation.json'),JSON.stringify(report,null,2));
  await browser.close();
  process.stdout.write(JSON.stringify({status:report.status,passed:checks.filter(check=>check.passed).length,total:checks.length,run_id:run.id,failed:checks.filter(check=>!check.passed)},null,2));
  process.exitCode=report.status==='PASS'?0:1;
})().catch(error=>{process.stderr.write(error.stack);process.exitCode=1;});
